export const CHAINS = ['eth', 'bsc', 'polygon'];
export const COLLECTIONS = [
  {
    chain: 'ETH',
    address: '0x3bf2922f4520a8BA0c2eFC3D2a1539678DaD5e9D',
    name: '0N1 Force',
    priority: 1,
    twitter_link: 'https://twitter_link.com/0n1Force',
    discord_link: 'https://discord.com/invite/0N1Force',
    website_link: '0N1FORCE.com',
  },
  {
    chain: 'ETH',
    address: '0x059EDD72Cd353dF5106D2B9cC5ab83a52287aC3a',
    name: 'Art Blocks',
    priority: 1,
    twitter_link: 'https://twitter_link.com/artblocks_io',
    discord_link: 'http://discord.gg/artblocks',
    website_link: 'artblocks.io',
  },
  {
    chain: 'ETH',
    address: '0xba30E5F9Bb24caa003E9f2f0497Ad287FDF95623',
    name: 'Bored Ape Kennel Club',
    priority: 1,
    twitter_link: 'https://twitter_link.com/boredapeyc',
    discord_link: 'https://discord.com/invite/wjH7hGz2yS',
    website_link: 'https://boredapeyachtclub.com/#/kennel-club',
  },
  {
    chain: 'ETH',
    address: '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D',
    name: 'Bored Ape Yacht Club',
    priority: 1,
    twitter_link: 'https://twitter_link.com/BoredApeYC',
    discord_link: 'http://discord.gg/bayc',
    website_link: 'boredapeyachtclub.com',
  },
  {
    chain: 'ETH',
    address: '0x1A92f7381B9F03921564a437210bB9396471050C',
    name: 'Cool Cats NFT',
    priority: 1,
    twitter_link: 'https://twitter_link.com/coolcatsnft',
    discord_link: 'http://discord.gg/coolcatsnft',
    website_link: 'store.coolcatsnft.com',
  },
  {
    chain: 'ETH',
    address: '0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB',
    name: 'CryptoPunks',
    priority: 1,
    twitter_link: 'https://twitter_link.com/larvalabs',
    discord_link: 'https://discord.com/invite/tQp4pSE',
    website_link: 'https://www.larvalabs.com/cryptopunks',
  },
  {
    chain: 'ETH',
    address: '0x79986af15539de2db9a5086382daeda917a9cf0c',
    name: 'Cryptovoxels',
    priority: 1,
    twitter_link: 'https://twitter_link.com/cryptovoxels',
    discord_link: 'https://discord.com/invite/rQVMQax',
    website_link: 'cryptovoxels.com',
  },
  {
    chain: 'ETH',
    address: '0xf3E6DbBE461C6fa492CeA7Cb1f5C5eA660EB1B47',
    name: 'Fame Lady Squad',
    priority: 1,
    twitter_link: 'https://twitter_link.com/fame_ladies',
    discord_link: 'http://discord.gg/fameladies',
    website_link: 'http://fameladysquad.com',
  },
  {
    chain: 'ETH',
    address: '0xC2C747E0F7004F9E8817Db2ca4997657a7746928',
    name: 'Hashmasks',
    priority: 1,
    twitter_link: 'https://twitter_link.com/TheHashmasks',
    discord_link: 'http://discord.gg/hashmasks',
    website_link: 'thehashmasks.com',
  },
  {
    chain: 'ETH',
    address: '0x7Bd29408f11D2bFC23c34f18275bBf23bB716Bc7',
    name: 'Meebits',
    priority: 1,
    twitter_link: 'https://twitter_link.com/MeebitsDAO',
    discord_link: 'https://discord.com/invite/tQp4pSE',
    website_link: 'meebitsdao.world',
  },
  {
    chain: 'ETH',
    address: '0x60E4d786628Fea6478F785A6d7e704777c86a7c6',
    name: 'Mutant Ape Yacht Club',
    priority: 1,
    twitter_link: 'https://twitter_link.com/BoredApeYC',
    discord_link: 'http://discord.gg/bayc',
    website_link: 'boredapeyachtclub.com',
  },
  {
    chain: 'ETH',
    address: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8',
    name: 'Pudgy Penguins',
    priority: 1,
    twitter_link: 'https://twitter_link.com/Pudgy_Penguins',
    discord_link: 'http://discord.gg/pudgypenguins',
    website_link: 'pudgypenguins.io',
  },
  {
    chain: 'ETH',
    address: '0xf497253C2bB7644ebb99e4d9ECC104aE7a79187A',
    name: 'The Sevens',
    priority: 1,
    twitter_link: 'https://twitter_link.com/thesevens_7',
    discord_link: 'https://discord.com/invite/777-thesevens-777',
    website_link: 'thesevensofficial.com',
  },
  {
    chain: 'ETH',
    address: '0x1B829B926a14634d36625e60165c0770C09D02b2',
    name: 'Treeverse',
    priority: 1,
    twitter_link: 'https://twitter_link.com/TheTreeverse',
    discord_link: 'discord.gg/5uPqqqzUyE',
    website_link: 'http://play.treeverse.net',
  },
  {
    chain: 'ETH',
    address: '0xa3AEe8BcE55BEeA1951EF834b99f3Ac60d1ABeeB',
    name: 'VeeFriends',
    priority: 1,
    twitter_link: 'https://twitter_link.com/veefriends',
    discord_link: 'https://discord.com/invite/veefriends',
    website_link: 'https://veefriends.com/',
  },
  {
    chain: 'ETH',
    address: '0xE3435EdBf54b5126E817363900234AdFee5B3cee',
    name: 'Voxies',
    priority: 1,
    twitter_link: 'https://twitter_link.com/VoxiesNFT',
    discord_link: 'http://discord.gg/q8Swd7vPDc',
    website_link: 'voxies.io',
  },
];
