steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/wallettracker-328605/$_SERVICE:latest',
        '--build-arg=REACT_APP_DCL_LAND_ADDRESS=$_REACT_APP_DCL_LAND_ADDRESS',
        '--build-arg=REACT_APP_DCL_LAND_RENTAL_ADDRESS=$_REACT_APP_DCL_LAND_RENTAL_ADDRESS',
        '--build-arg=REACT_APP_HOLDINGS_SERVICE_API=$_REACT_APP_HOLDINGS_SERVICE_API',
        '--build-arg=REACT_APP_HOLDINGS_SERVICE_SOCKET=$_REACT_APP_HOLDINGS_SERVICE_SOCKET',
        '--build-arg=REACT_APP_USDT_ADDRESS=$_REACT_APP_USDT_ADDRESS',
        '--build-arg=REACT_APP_USDT_DECIMALS=$_REACT_APP_USDT_DECIMALS',
        '.',
      ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/wallettracker-328605/$_SERVICE:latest']
images:
  - 'gcr.io/wallettracker-328605/$_SERVICE:latest'
timeout: 1200s
substitutions:
  _REACT_APP_DCL_LAND_ADDRESS: ""
  _REACT_APP_DCL_LAND_RENTAL_ADDRESS: ""
  _REACT_APP_HOLDINGS_SERVICE_API: ""
  _REACT_APP_HOLDINGS_SERVICE_SOCKET: ""
  _REACT_APP_USDT_ADDRESS: ""
  _REACT_APP_USDT_DECIMALS: "18"
  _SERVICE: ''

