# build environment
FROM node:12-alpine as react-build
WORKDIR /app
COPY ./client ./

RUN yarn

ARG REACT_APP_HOLDINGS_SERVICE_API
ENV REACT_APP_HOLDINGS_SERVICE_API=$REACT_APP_HOLDINGS_SERVICE_API

ARG REACT_APP_HOLDINGS_SERVICE_SOCKET
ENV REACT_APP_HOLDINGS_SERVICE_SOCKET=$REACT_APP_HOLDINGS_SERVICE_SOCKET

ARG REACT_APP_DCL_LAND_RENTAL_ADDRESS
ENV REACT_APP_DCL_LAND_RENTAL_ADDRESS=$REACT_APP_DCL_LAND_RENTAL_ADDRESS

ARG REACT_APP_DCL_LAND_ADDRESS
ENV REACT_APP_DCL_LAND_ADDRESS=$REACT_APP_DCL_LAND_ADDRESS

ARG REACT_APP_USDT_ADDRESS
ENV REACT_APP_USDT_ADDRESS=$REACT_APP_USDT_ADDRESS

ARG REACT_APP_USDT_DECIMALS
ENV REACT_APP_USDT_DECIMALS=$REACT_APP_USDT_DECIMALS

# to be removed
ARG SKIP_PREFLIGHT_CHECK
ENV SKIP_PREFLIGHT_CHECK=$SKIP_PREFLIGHT_CHECK

ARG REACT_APP_DEFAULT_WEB3_PROVIDER
ENV REACT_APP_DEFAULT_WEB3_PROVIDER=$REACT_APP_DEFAULT_WEB3_PROVIDER

ARG REACT_APP_POLYGON_PROVIDER
ENV REACT_APP_POLYGON_PROVIDER=$REACT_APP_POLYGON_PROVIDER

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

ARG REACT_APP_MORALIS_SERVER_URL
ENV REACT_APP_MORALIS_SERVER_URL=$REACT_APP_MORALIS_SERVER_URL

ARG REACT_APP_MORALIS_APPLICATION_ID
ENV REACT_APP_MORALIS_APPLICATION_ID=$REACT_APP_MORALIS_APPLICATION_ID

ARG REACT_APP_MORALIS_API_KEY
ENV REACT_APP_MORALIS_API_KEY=$REACT_APP_MORALIS_API_KEY

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

ARG REACT_APP_CONTRACT_SERVICE_API
ENV REACT_APP_CONTRACT_SERVICE_API=$REACT_APP_CONTRACT_SERVICE_API


RUN yarn build

# server environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/configfile.template

COPY --from=react-build /app/build /usr/share/nginx/html

ENV PORT 8080
ENV HOST 0.0.0.0

EXPOSE 8080
CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"