# build environment
FROM node:12-alpine as react-build
WORKDIR /app
COPY . ./

ARG REACT_APP_HOLDINGS_SERVICE_API
ENV REACT_APP_HOLDINGS_SERVICE_API=$REACT_APP_HOLDINGS_SERVICE_API

ARG REACT_APP_HOLDINGS_SERVICE_SOCKET
ENV REACT_APP_HOLDINGS_SERVICE_SOCKET=$REACT_APP_HOLDINGS_SERVICE_SOCKET

ARG REACT_APP_DCL_LAND_RENTAL_ADDRESS
ENV REACT_APP_DCL_LAND_RENTAL_ADDRESS=$REACT_APP_DCL_LAND_RENTAL_ADDRESS

ARG REACT_APP_DCL_LAND_ADDRESS
ENV REACT_APP_DCL_LAND_ADDRESS=$REACT_APP_DCL_LAND_ADDRESS

ARG REACT_APP_USDT_ADDRESS
ENV REACT_APP_USDT_ADDRESS=$REACT_APP_USDT_ADDRESS

ARG REACT_APP_USDT_DECIMALS
ENV REACT_APP_USDT_DECIMALS=$REACT_APP_USDT_DECIMALS

RUN echo $REACT_APP_HOLDINGS_SERVICE_API $REACT_APP_HOLDINGS_SERVICE_SOCKET $REACT_APP_DCL_LAND_RENTAL_ADDRESS $REACT_APP_DCL_LAND_ADDRESS $REACT_APP_USDT_ADDRESS $REACT_APP_USDT_DECIMALS

RUN yarn
RUN yarn build

# server environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/configfile.template

COPY --from=react-build /app/build /usr/share/nginx/html

ENV PORT 8080
ENV HOST 0.0.0.0

EXPOSE 8080
CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"