# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: doko-client
  RUN_REGION: asia-southeast1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Info
      run: gcloud info
      
    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --substitutions=_SKIP_PREFLIGHT_CHECK=true \
          --substitutions=_REACT_APP_DEFAULT_WEB3_PROVIDER=https://mainnet.infura.io/v3/c567961fd5e6427b8f20575180a31787 \
          --substitutions=_REACT_APP_POLYGON_PROVIDER=https://polygon-mainnet.infura.io/v3/c567961fd5e6427b8f20575180a31787 \
          --substitutions=_NODE_ENV=production \
          --substitutions=_REACT_APP_MORALIS_SERVER_URL=https://aqho5ffgvcnl.bigmoralis.com:2053/server \
          --substitutions=_REACT_APP_MORALIS_APPLICATION_ID=EDNVamX6PUBpWYEe85Up5l4O7FxsVkbZ9ch1vaVe \
          --substitutions=_REACT_APP_MORALIS_API_KEY=f50VqTEOHQxCtiETP2xYDlhA9n1wqiZfmAQAsTpfcJNksapuS2RR6ohCwezlTZN7 \
          --substitutions=_REACT_APP_API_URL=https://doko.one \
          --substitutions=_REACT_APP_CONTRACT_SERVICE_API=https://holdings-service-df63favl7q-df.a.run.app \
          --substitutions=_SERVICE=doko-client \
          --timeout=20m  
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/wallettracker-328605/doko-client:latest" \
          --platform "managed" \
          --port 80 \
          --allow-unauthenticated
  
